name: recipe_book
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  get: 4.6.6
  flutter_form_builder: 9.4.1
  form_builder_validators: 11.0.0
  hive_ce: 2.5.0+2
  hive_ce_flutter: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
